### ISSUE TITLE
Inscripción de Estudiantes Semestre 2019-II.

### ISSUE THREAD

**Issue by ejdecena** [ejdecena/calculo_numerico#1]
Un cordial saludo para todos.

Los estudiantes de la asignatura de **Cálculo Numérico** deberán agregar a este **Issue** los siguientes datos:

* Su nombre completo.
* Su número de cédula.
* Link de su repositorio en *GitHub* con la nomenclatura **calculo_nombre_apellido**.

Estos datos son necesarios para incorporarlos a las planillas de evaluación de la asignatura [**aquí.**](https://github.com/ejdecena/calculo_numerico/tree/master/evaluaciones)

**NOTA 1:** El plazo para incorporar estos datos es hasta el día **viernes 18 de Octubre de 2019**.

**NOTA 2:** Para poder recibir las actualizaciones de este repositorio, los participantes deben marcar este repositorio con **Watch** y **Star** para suscribir las notificaciones.

Gracias de antemano.

**Comment by Hsalazar-hub** [comment]
Hèctor David Salazar Rodrìguez
CI: 25967387
https://github.com/Hsalazar-hub/calculo_hector_salazar

**Comment by Siaper** [comment]
Miguel Humberto Bruno C.I: 26842695 link del repositorio: https://github.com/Siaper/Calculo_Miguel_Bruno

**Comment by xeastx** [comment]
Enrique Antonio Salazar Tillero  C.I: 27000054 
https://github.com/xeastx/calculo_Enrique_Salazar

**Comment by Ramsest01** [comment]
Estéfano Valentino Ramos Guarín
C.I. 26778542
https://github.com/Ramsest01/Calculo_Estefano_Ramos

**Comment by norlierojas** [comment]
Norlie Mercedes Rojas Gil C.I: 26707950
https://github.com/norlierojas/calculo_norlie_rojas

**Comment by Al3x28** [comment]
Alejandro Ernesto Girardi Castillo C.I:27525819
https://github.com/Al3x28/calculo_Alejandro_Girardi.git

**Comment by wuilmerpulgar** [comment]
Wuilmer Asdrubal Pulgar Avila C.I: 26625191
https://github.com/wuilmerpulgar/calculo_wuilmer_pulgar

**Comment by jrmmauricio** [comment]
Mauricio Junior Marcano Zabala C.I V27202233
https://github.com/jrmmauricio/calculo_mauricio_marcano

**Comment by Danilo9901** [comment]
Danilo Andres López Flores  C.I : 27424264
https://github.com/Danilo9901/Calculo_danilo_lopez.git

**Comment by anibalvc** [comment]
Anibal Jose Velasquez Carrion
C.I: 26887484
https://github.com/anibalvc/Calculo_Anibal_Velasquez

**Comment by ejdecena** [comment]
#### RECORDATORIO DE ENVIADO DE DATOS.
Saludos amigos.

**NOTA 1**: Recuerden por favor que el **plazo** para enviar los datos es hasta **mañana viernes, 18 de octubre de 2019**. Por si conocen a alguien que aún no haya hecho el registro, hacerle por favor el recordatorio.

**NOTA 2**: Es conveniente recordar que para recibir las **notificaciones** de este repositorio deben hacer click en el **Watch** y **Star** del mismo, así como también dar **Follow** a mi perfil, para de esta manera yo validar que están linkeados con todos los repositorios. Hasta ahora hay 10 participantes en este **Issue**, con lo cual deberían haber igual número de **Watch** y **Star**.

Gracias de antemano.

**Comment by ejdecena** [comment]
#### CREACIÓN DEL REPOSITORIO LOCAL.

**NOTA 1**. Ahora que ya tienen sus repositorios remotos creados en *GitHub*, es conveniente ahora que creen los **repositorios locales** en sus respectivos computadores, por si todavía aún no lo han creado. Básicamente así funciona *GitHub*: con el **par** *remoto-local* linkeados. En el [**Tutorial Git**](https://github.com/ejdecena/tutorial_git/blob/master/repositorios_locales.md#cabecera) están las instrucciones para crear los repositorios locales. **Cualquier duda o pregunta, la pueden hacer directamente por este medio, que para eso es esta herramienta.**

**NOTA 2**. El día lunes les asignaré la primera actividad remota del curso. Esta actividad consistirá básicamente de **dos** tareas:
1. Actualizar su repositorio remoto en *GitHub* con un archivo `README.md` desde su repositorio local. Para esta tarea deben conocer los comandos `git add`, `git commit`y `git push` que pueden revisar en el  [**Tutorial Git**](https://github.com/ejdecena/tutorial_git/blob/master/flujo_trabajo_local.md#cabecera). El **formato** del archivo `README.md`es el *Markdown*. En internet hay mucha información sobre este formato, aquí apenas una breve [**Guía de Markdown**](https://www.genbeta.com/guia-de-inicio/que-es-markdown-para-que-sirve-y-como-usarlo).
2. La segunda tarea consistirá en hacer un flujo de trabajo *fork-pull-request*. Para ello crearé un repositorio de prueba y luego les daré las instrucciones detalladas el día lunes.

Mientras tanto pueden ir trabajando en la **tarea 1** para ir adelantando :)
Les reitero una vez más que **cualquier duda o pregunta la pueden hacer directamente por este medio.**

Un saludo para tod@s.

**Comment by DiegoTineo** [comment]
Diego Alejandro Tineo Zabala C.I V27650623
https://github.com/DiegoTineo/Calculo_Diego_Tineo

**Comment by hemeh12** [comment]
Jose Angel Guevara Moya C.I V-27525799
https://github.com/hemeh12/calculo--jose-guevara

**Comment by ashlyelizabeth** [comment]
Ashly Scarpati 
Ci 27424492
https://github.com/ashlyelizabeth/calculo_ashly_scarpati

**Comment by ejdecena** [comment]
#### ACTUALIZACIÓN DE DATOS.

Hola amigos.

Los datos de los participantes de este curso fueron actualizados en [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/evaluaciones/participantes.csv), por favor chequearse y en caso de que sus datos no aparezcan notificarlo por este medio.

Gracias de antemano.

**Comment by JCalderin91** [comment]
Jesus Rafael Calderin Anton
C.I. 22.998.438
https://github.com/JCalderin91/calculo_jesus_calderin

**Comment by ejdecena** [comment]
#### PROYECTO WORKFLOW PULL-REQUEST.

Hola amigos. Ya está publicado el [**Proyecto Workflow Pull-Request**](https://github.com/ejdecena/proyecto_calculo).

Saludos.

**Comment by ejdecena** [comment]
#### META PROGRAMACIÓN.
A manera de aprendizaje adicional (ya que no tiene nada que ver con Cálculo Numérico), es que el **código** del *Proyecto Workflow Pull-Request* fue creado con **otro código**, el cual pueden ver [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/codigos/generar_proyecto_pr.py); es decir, se trata de un programa que genera **otro programa**, es lo que se conoce como [*Metaprogramación*](https://es.wikipedia.org/wiki/Metaprogramaci%C3%B3n). Supongo que verán ese tema en la asignatura de *Lenguajes de Programación*.

**Comment by cesaralbornoz** [comment]
Cesar Ramón albornoz Benítez
CI: 26311747
https://github.com/cesaralbornoz/calculo_cesar_albornoz

**Comment by ejdecena** [comment]
> Cesar Ramón albornoz Benítez
> CI: 26311747
> https://github.com/cesaralbornoz/calculo_cesar_albornoz

El problema es que como no te inscribiste a tiempo, para este proyecto no se te generó una función... Pendiente para el proyecto de la semana que viene.

**Comment by ejdecena** [comment]
#### LECTURA.
Saludos amigos. Veo que están un poco *crudos* con el lenguaje Python. Les recomiendo que se tomen un tiempo para leer el manual [**_Python para Todos_**](https://github.com/ejdecena/tutorial_python/blob/master/documentos/libro_python_para_todos.pdf) el cual está en mi repositorio. Iremos progresivamente haciendo más proyectos, por lo que es conveniente que se empapen suficientemente del lenguaje para ir desarrollando los proyectos más fluidamente.
Gracias.

**Comment by josemvegar** [comment]
josé manuel vega regnault
27000723
https://github.com/josemvegar/calculo_jose_vega

**Comment by ejdecena** [comment]
> josé manuel vega regnault
> 27000723
> https://github.com/josemvegar/calculo_jose_vega

Aplica lo mismo que @cesaralbornoz.

**Comment by ejdecena** [comment]
#### LOS DOCSTRING.
Los **docstring** son _cadenas de documentación_ para documentar el código *Python*, tal y como dice en este [**enlace**](http://edupython.blogspot.com/2013/12/documentando-programas-en-python.html):
> **Cadenas de documentación.**
En Python, un docstring o cadena de documentación es una literal de cadena de caracteres que se **coloca como primer enunciado de un módulo, clase, método o función**, y cuyo propósito es explicar su intención...

Es importante lo que está en **negrita** en la cita, para que una cadena sea **docstring** debe ser el **primer enunciado de un módulo, clase, método o función**, si no es así **no** es docstring.

Los **docstring** son importantes para documentar el código de proyectos colaborativos, cuando la gente trabaja en remoto, como estamos haciendo nosotros en el [proyecto_calculo](https://github.com/ejdecena/proyecto_calculo). Por ejemplo, en el archivo [proyecto_calculo.py](https://github.com/ejdecena/proyecto_calculo/blob/master/proyecto_calculo.py) la línea 2 es el **docstring** del módulo (archivo). Del mismo modo, cada función en ese archivo tiene su **docstring**, porque es la **primera linea** luego de la declaración.

En este [**enlace**](https://python-para-impacientes.blogspot.com/2014/02/docstrings.html) hay información adicional sobre los **docstring**.

**Comment by lromeroy** [comment]
Luis Pablo Romero Yezzi
C.I: 26.625.100
https://github.com/lromeroy/calculo_luis_romero

**Comment by ejdecena** [comment]
> Luis Pablo Romero Yezzi
> C.I: 26.625.100
> https://github.com/lromeroy/calculo_luis_romero

Aplica lo mismo que @cesaralbornoz.
Debes dar **Watch** y **Star** a este repositorio y  **Follow** en mi perfil para recibir todas las notificaciones. Gracias.

**Comment by kvnatera03** [comment]
Kevin Ricardo Natera Ramos
C.I: 27.000.066
https://github.com/kvnatera03/calculo_kevin_natera

**Comment by ejdecena** [comment]
> 27.000.066

El nombre del repositorio **no cumple con el formato**. Y aplica lo mismo que @cesaralbornoz.

**Comment by ejdecena** [comment]
#### FIN DEL PERÍODO DE INSCRIPCIÓN.
Claramente se dijo [**aquí**](https://github.com/ejdecena/calculo_numerico/issues/1#issue-506906663) que la fecha de inscripción en esta asignatura era hasta el día **viernes 18 de octubre**, de tal manera que a partir de ahora ya no se aceptarán nuevas inscripciones.

**Comment by ejdecena** [comment]
#### NUEVO ISSUE.
Hola. Ha terminado el **Proyecto 1**. He creado este [**nuevo issue**](https://github.com/ejdecena/calculo_numerico/issues/4#issue-512274805) donde publicaré las notas de las evaluaciones. Nos vemos el lunes en horas de clase.

¡FELIZ FIN DE SEMANA! :+1:

**Comment by ejdecena** [comment]
#### SOBRE LA ORIGINALIDAD DE LOS CÓDIGOS.
Los códigos y aportes de cada participante en los proyectos **deben ser originales y propios de cada participante**. Las **copias** o **intentos de copia** serán **penalizados duramente**. Hay que advertir que *GitHub* marca con un [**hash**](https://www.genbeta.com/desarrollo/que-son-y-para-que-sirven-los-hash-funciones-de-resumen-y-firmas-digitales) (huella digital única) los aportes de los programadores, de tal manera que los códigos iguales [**o similares**](https://github.com/ejdecena/proyecto_calculo/pull/14/files#r338874216) disparan un **alerta** en *GitHub* que es **imposible evadir**.

Así que, por favor, eviten penalizaciones innecesarias.
Gracias de antemano.

**Comment by ejdecena** [comment]
#### PROYECTO ALGORITMO DE BISECCIÓN.
Hola amigos. Ya se encuentra publicado el [**Proyecto Algoritmo de Bisección**](https://github.com/ejdecena/proyecto_biseccion). El plazo para la entrega de este proyecto es hasta el día **sábado 02 de noviembre de 2019, 11:59pm**. En el repositorio del proyecto se encuentran todas las instrucciones del mismo. Cualquier duda o pregunta la hacen por favor a través de la apertura de un **issue** en el repositorio del proyecto.

Gracias de antemano.
Saludos.

**Comment by ejdecena** [comment]
#### WORKFLOW DEL PROYECTO ALGORITMO DE BISECCIÓN.
El workflow a seguir para la entrega del *Proyecto Algoritmo de Bisección* se especifica en este [**issue**](https://github.com/ejdecena/proyecto_biseccion/issues/1).

Saludos.

**Comment by ejdecena** [comment]
> #### SOBRE LA ORIGINALIDAD DE LOS CÓDIGOS.
> Los códigos y aportes de cada participante en los proyectos **deben ser originales y propios de cada participante**. Las **copias** o **intentos de copia** serán **penalizados duramente**. Hay que advertir que _GitHub_ marca con un [**hash**](https://www.genbeta.com/desarrollo/que-son-y-para-que-sirven-los-hash-funciones-de-resumen-y-firmas-digitales) (huella digital única) los aportes de los programadores, de tal manera que los códigos iguales [**o similares**](https://github.com/ejdecena/proyecto_calculo/pull/14/files#r338874216) disparan un **alerta** en _GitHub_ que es **imposible evadir**.
> 
> Así que, por favor, eviten penalizaciones innecesarias.
> Gracias de antemano.

Ya había advertido sobre **evitar penalizaciones** innecesarias al intentar [**copiar código**](https://github.com/ejdecena/proyecto_biseccion/pull/8) en *GitHub* o en Internet, @Siaper, ENTIENDE: **la plataforma marca con un HASH los códigos fuentes, tanto en la plataforma como en los que se encuentran en Internet, y este mecanismo NO SE PUEDE EVADIR,** por tanto **¡¡¡ LA GENTE NO PUEDE COPIARSE LOS CÓDIGOS !!!**

**Comment by ejdecena** [comment]
> > #### SOBRE LA ORIGINALIDAD DE LOS CÓDIGOS.
> > Los códigos y aportes de cada participante en los proyectos **deben ser originales y propios de cada participante**. Las **copias** o **intentos de copia** serán **penalizados duramente**. Hay que advertir que _GitHub_ marca con un [**hash**](https://www.genbeta.com/desarrollo/que-son-y-para-que-sirven-los-hash-funciones-de-resumen-y-firmas-digitales) (huella digital única) los aportes de los programadores, de tal manera que los códigos iguales [**o similares**](https://github.com/ejdecena/proyecto_calculo/pull/14/files#r338874216) disparan un **alerta** en _GitHub_ que es **imposible evadir**.
> > Así que, por favor, eviten penalizaciones innecesarias.
> > Gracias de antemano.
> 
> Ya había advertido sobre **evitar penalizaciones** innecesarias al intentar [**copiar código**](https://github.com/ejdecena/proyecto_biseccion/pull/8) en _GitHub_ o en Internet, @Siaper, ENTIENDE: **la plataforma marca con un HASH los códigos fuentes, tanto en la plataforma como en los que se encuentran en Internet, y este mecanismo NO SE PUEDE EVADIR,** por tanto **¡¡¡ LA GENTE NO PUEDE COPIARSE LOS CÓDIGOS !!!**

Lo  [**MISMO**](https://github.com/ejdecena/proyecto_biseccion/pull/15#issuecomment-549048989) aplica para @kvnatera03.

**NOTA**: Si algunos participantes de este grupo **insisten en romper las reglas** claramente establecidas desde el principio, se dará esta actividad **por concluida** para **todo** el curso y se hará un **reporte** completo para la Coordinación de Informática.

**Comment by ejdecena** [comment]
#### CORRECCIÓN DEL PROYECTO 2.
Saludos. Los algoritmos del **Proyecto 2** fueron corregidos uno a uno; los resultados se muestran [**aquí**](https://github.com/ejdecena/proyecto_biseccion/tree/master/tests). Las **notas** del **Proyecto 2** ya fueron procesadas [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/evaluaciones/proyectos.csv). Cualquier duda o petición sobre el **Proyecto 2** pueden canalizarla abriendo un [**issue**](https://github.com/ejdecena/calculo_numerico/issues) en este repositorio.

**OBSERVACIONES:**
* Hay participantes interesados en aprender e hicieron un buen trabajo.
* Aún se observa poca destreza con el lenguaje *Python*, hay que leer el manual [**Python Para Todos.**](https://github.com/ejdecena/tutorial_python/blob/master/documentos/libro_python_para_todos.pdf)
* Hay unas **reglas** claramente establecidas para seguir este curso. LEERLAS no cuesta nada.
* Es una muy mala idea copiar o intentar copiar código. Ya conocen las consecuencias.
* Los algoritmos deben **probarse** antes de ser enviados al PR.
* Es una muy mala idea que dos o más participantes trabajen desde una **misma conexión de Internet.**

**PRÓXIMA ACTIVIDAD:**
Mañana lunes 04 de noviembre, en horas de clase, estaremos viendo el *Algoritmo de Newton-Raphson*, haremos unos ejercicios y asignaremos el *Proyecto 3* para esta semana.

### ¡Feliz domingo! :sunglasses:

**Comment by mjmife** [comment]
Mariangeles Millan Fermin
C.I: 20901641
Link: https://github.com/mjmife/calculo_mariangeles_millan

**Comment by supereliel** [comment]
- Eliel IsacarAlfonzo Suarez

- 20326345

- https://github.com/supereliel/calculo_eliel_alfonzo

**Comment by supereliel** [comment]
> #### META PROGRAMACIÓN.
> 
> A manera de aprendizaje adicional (ya que no tiene nada que ver con Cálculo Numérico), es que el **código** del _Proyecto Workflow Pull-Request_ fue creado con **otro código**, el cual pueden ver [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/codigos/generar_proyecto_pr.py); es decir, se trata de un programa que genera **otro programa**, es lo que se conoce como [_Metaprogramación_](https://es.wikipedia.org/wiki/Metaprogramaci%C3%B3n). Supongo que verán ese tema en la asignatura de _Lenguajes de Programación_.

Profe el enlace del programa no funciona ¿Puede corregirlo para ver ese código?

**Comment by ejdecena** [comment]
#### SOLICITUD DE HABILIDADES TÉCNICAS.
Los aspirantes deben poseer conocimientos de:
* HTML.
* CSS.
* Conocimiento básico del *Wordrpress*.
* Javascript básico, y conocimiento básico del framework *JQuery*.
* Deseable conocimiento básico de *Php*.

El trabajo es **presencial**, de *lunes* a *viernes*, de *8:00 am* a *5:00 pm*. Los **estudiantes** podrán tener algunas excepciones con el horario, el cual podrá convenirse.

![WhatsApp Image 2019-11-05 at 12 54 31 PM](https://user-images.githubusercontent.com/8931673/68228910-a2b9af00-ffcc-11e9-9cb1-1b1177bcbfb1.jpeg)

#### BENEFICIOS:
* 40$ mensuales.
* Bono de productividad.

**Comment by ejdecena** [comment]
> > #### META PROGRAMACIÓN.
> > A manera de aprendizaje adicional (ya que no tiene nada que ver con Cálculo Numérico), es que el **código** del _Proyecto Workflow Pull-Request_ fue creado con **otro código**, el cual pueden ver [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/codigos/generar_proyecto_pr.py); es decir, se trata de un programa que genera **otro programa**, es lo que se conoce como [_Metaprogramación_](https://es.wikipedia.org/wiki/Metaprogramaci%C3%B3n). Supongo que verán ese tema en la asignatura de _Lenguajes de Programación_.
> 
> Profe el enlace del programa no funciona ¿Puede corregirlo para ver ese código?

Después te lo paso @supereliel.

**Comment by ejdecena** [comment]
#### PROYECTO DE NEWTON-RAPHSON.
Ya está publicado el [**Proyecto de Newton-Raphson**](https://github.com/ejdecena/proyecto_newton_raphson). Las copias de código serán **penalizadas severamente**, sea ordenado y evite el [*Código Espagueti*](https://es.wikipedia.org/wiki/C%C3%B3digo_espagueti).

Saludos.

**Comment by ejdecena** [comment]
#### CORRECCIÓN DEL PROYECTO 3.
Saludos amigos. Los algoritmos del **Proyecto 3** fueron corregidos uno a uno; los resultados se muestran [**aquí**](https://github.com/ejdecena/proyecto_newton_raphson/tree/master/tests). Las **notas** del **Proyecto 3** ya fueron procesadas [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/evaluaciones/proyectos.csv). Cualquier duda o petición sobre el **Proyecto 3** pueden canalizarla abriendo un [**issue**](https://github.com/ejdecena/calculo_numerico/issues) en este repositorio.

**PRÓXIMA ACTIVIDAD:**
El **lunes 11 de noviembre de 2019**, en horas de clase, estaremos viendo el *Polinomio de Taylor* (Guía 1), haremos unos ejercicios y asignaremos el *Proyecto 4* para esa semana.

### ¡Saludos! :sunglasses:

**Comment by ejdecena** [comment]
#### CLASE DE MAÑANA.
Saludos amigos. Me confirman por favor la hora de la clase de mañana, mientras más temprano en la mañana mejor. Gracias.

**NOTA:** Aquí un interesante link que encontré por ahí, [**_El módulo Python 3 de la semana_**](https://rico-schmidt.name/pymotw-3/).

**Comment by Siaper** [comment]
Buenas tardes profesor, la clase de mañana es a las 10:45 a.m, no creo que podamos verla más temprano ya que mis otros compañeros, que tambien estan viendo calculo, tienen clases más temprano de lenguaje de programacion en teoria

**Comment by ejdecena** [comment]
> #### CLASE DE MAÑANA.
> Saludos amigos. Me confirman por favor la hora de la clase de mañana, mientras más temprano en la mañana mejor. Gracias.
> 
> **NOTA:** Aquí un interesante link que encontré por ahí, [**_El módulo Python 3 de la semana_**](https://rico-schmidt.name/pymotw-3/).

Si empezamos a las **10:30 am** podríamos terminar antes del medio día.

**Comment by supereliel** [comment]
> #### CLASE DE MAÑANA.
> 
> Saludos amigos. Me confirman por favor la hora de la clase de mañana, mientras más temprano en la mañana mejor. Gracias.
> 
> **NOTA:** Aquí un interesante link que encontré por ahí, [**_El módulo Python 3 de la semana_**](https://rico-schmidt.name/pymotw-3/).

¿10:00 a.m. pudiera ser?

**Comment by JCalderin91** [comment]
Yo no puedo antes de las 10:45, lo siento

**Comment by ejdecena** [comment]
> > #### CLASE DE MAÑANA.
> > Saludos amigos. Me confirman por favor la hora de la clase de mañana, mientras más temprano en la mañana mejor. Gracias.
> > **NOTA:** Aquí un interesante link que encontré por ahí, [**_El módulo Python 3 de la semana_**](https://rico-schmidt.name/pymotw-3/).
> 
> Si empezamos a las **10:30 am** podríamos terminar antes del medio día.

Ok, mañana empezaremos entonces a la hora reglamentaria, **10:45 am**.

**Comment by ejdecena** [comment]
#### PROYECTO DEL POLINOMIO DE TAYLOR.
Saludos amigos. Ya está publicado el [**Proyecto del Polinomio de Taylor**](https://github.com/ejdecena/proyecto_polinomio_taylor). Nuevamente, las **copias de código** serán **penalizadas severamente**. Sea ordenado y coherente en la codificación de los algoritmos. Comente, documente y evite el [*Código Espagueti*](https://es.wikipedia.org/wiki/C%C3%B3digo_espagueti).

Saludos.

**Comment by ejdecena** [comment]
#### CORRECCIÓN DEL PROYECTO 4.
Saludos amigos. Los algoritmos del **Proyecto 4** fueron corregidos uno a uno; los resultados se muestran [**aquí**](https://github.com/ejdecena/proyecto_polinomio_taylor/tree/master/tests). Las **notas** del **Proyecto 4** ya fueron procesadas [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/evaluaciones/proyectos.csv). Cualquier duda o petición sobre el **Proyecto 4** pueden canalizarla abriendo un [**issue**](https://github.com/ejdecena/calculo_numerico/issues) en este repositorio.

**PRÓXIMA ACTIVIDAD:**
**Hoy lunes 18 de noviembre de 2019**, en horas de clase, estaremos viendo el *Polinomio de Lagrange*, haremos unos ejercicios y asignaremos el *Proyecto 5* para esta semana.

### ¡Nos vemos en unas horas! :sunglasses:

**Comment by ejdecena** [comment]
#### PROYECTO POLINOMIO DE LAGRANGE.
Saludos amigos. Ya está publicado el [**Proyecto Polinomio de Lagrange**](https://github.com/ejdecena/proyecto_polinomio_lagrange). Nuevamente, las **copias de código** serán **penalizadas severamente**. Sea ordenado y coherente en la codificación de los algoritmos. Comente, documente y evite el [*Código Espagueti*](https://es.wikipedia.org/wiki/C%C3%B3digo_espagueti).

**NOTA**: Al inicio de las **líneas 17 y 24**, delante de:
```python
if len(X) != len(Y): raise ValueError("Dimensiones diferentes en X e Y.")

y

def polinomio(x):
```
hay **un espacio demás**, solo deben quitar este espacio en cada una de estas dos líneas para que todo funcione bien y no haya problemas.

Saludos.

**Comment by ejdecena** [comment]
#### CORRECCIÓN DEL PROYECTO 5.
Saludos amigos. Los algoritmos del **Proyecto 5** ya fueron corregidos uno a uno; los resultados se muestran [**aquí**](https://github.com/ejdecena/proyecto_polinomio_lagrange/tree/master/tests). Las **notas** del **Proyecto 5** ya fueron procesadas [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/evaluaciones/proyectos.csv). Cualquier duda o petición sobre el **Proyecto 5** pueden canalizarla abriendo un [**issue**](https://github.com/ejdecena/calculo_numerico/issues) en este repositorio.

**PRÓXIMA ACTIVIDAD:**
Ya tenemos todo listo para hacer el **primer examen escrito**. Haremos un repaso de todo el día **lunes 25 de noviembre de 2019** en horas de clase, y ese mismo día nos pondremos de acuerdo sobre las **pautas** para hacer el examen, que debería ser a más tardar el día **viernes 29 de noviembre de 2019**, aunque si lo podemos hacer antes, mejor.

### ¡Feliz Fin de Semana! :sunglasses:

**Comment by ejdecena** [comment]
#### EXÁMEN DEL VIERNES 29-NOV-2019.

Por favor llevar hoja de exámen tipo lapso, de esas que se usan en el liceo.
Gracias.

**Comment by ejdecena** [comment]
#### CORRECCIÓN DEL EXAMEN PARCIAL I (25%).
Saludos amigos. Los exámenes del **PARCIAL I (25%)** ya fueron corregidos uno a uno; las notas se muestran [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/evaluaciones/evaluaciones.csv).

**PRÓXIMA ACTIVIDAD:**
Mañana **lunes, 2 de diciembre de 2019** en horas de clase, resolveremos el examen y llevaré sus notas para aquellos que deseen revisar su corrección. 

### ¡Feliz Domingo! :sunglasses:

**Comment by ejdecena** [comment]
#### NOTAS DEFINITIVAS DE CÁLCULO NUMÉRICO.

Saludos amigos.Las notas definitivas de cálculo numérico se muestran [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/evaluaciones/evaluaciones.csv).

#### Saludos!

**Comment by xeastx** [comment]
Saludos profesor ✌️
