### ISSUE TITLE
Nota del primer proyecto

### ISSUE THREAD

**Issue by Al3x28** [ejdecena/calculo_numerico#5]
Muy buenos días, Prof.Decena es el estudiante Alejandro Girardi CI 27525819, me gustaría saber porque en la tabla de nota del proyecto, no tengo nota cuando entregué mi función

**Comment by ejdecena** [comment]
Hola. Voy a chequear.

**Comment by ejdecena** [comment]
Sí Alejandro, hay una **omisión** de mi parte en las notas y me falta tu calificación, ya encontré [**tu pull-request**](https://github.com/ejdecena/proyecto_calculo/pull/11). **Deja este issue abierto** por favor hasta que yo incluya tu nota en las próximas horas. Disculpa la omisión.
Gracias por notificarlo.

**Comment by ejdecena** [comment]
Saludos @Al3x28, tu nota ya fue actualizada [**aquí**](https://github.com/ejdecena/calculo_numerico/blob/master/evaluaciones/proyectos.csv), por favor chequear.

**Comment by Al3x28** [comment]
Muchas gracias profesor
