### ISSUE TITLE
Resultado del 2dro proyecto

### ISSUE THREAD

**Issue by JCalderin91** [ejdecena/calculo_numerico#7]
Buenos días, en su prueba el algoritmo falla en los 3 casos, estuve realizando pruebas en local con los archivos del repositorio y los resultados obtenidos son una ejecución completa y sin errores que causen la excepciones; En los casos A y B, las raíces son coinciden en su totalidad con las de sus resultados, para el caso C se presenta una diferencia evidente en las raíces. Por favor, solicito una aclaración, saludos.

_Nota: use mi algoritmo y su archivo de test para verificar los resultados_

**Comment by ejdecena** [comment]
Hola Jesús. Voy a revisar de nuevo tu algoritmo.

**Comment by JCalderin91** [comment]
Ya encontré el error, el algoritmo "funciona", el problema es el ámbito del método f, al ejecutar el método rango(), dice que f no está definido.
Al ejecutar el archivo no se presenta ese problema, el problema se da al ser importado como módulo.

Algo nuevo que aprender del lenguaje para mí.

**Comment by ejdecena** [comment]
Al revisar tú código, estos fueron los resultados que se obtuvieron:

| Caso | Tu Resultado | Resultado Esperado | Error %|
| --- | --- | --- | --- |
| Caso 0 | 1.96875 | 1.296875 | 51.81 |
| Caso 1 | 0.921875 | 0.7421875 | 24.21 |
| Caso 2 | -0.4609375 | -0.166015625 | 177.65 |

**HASH SHA256** `Jesus_22998438.py`: edf4dc8fe0731cd6707a33f9d73c604cf85b44676021a4df989d329ca8c2da69

Como puedes ver en la columna del **Error %**, los resultados no son satisfactorios.

**Comment by JCalderin91** [comment]
Si, profesor, el error fue definir el método f(x) dentro de él main.
cómo dije, el algoritmo está correcto, mas no lo está la ubicación de la definición de ese método.

**Comment by ejdecena** [comment]
Bueno realmente no me puse a indagar sobre dónde está el error; eso le corresponderá a cada participante hacerlo. Yo me limito a hacer las pruebas y a comparar los resultados.

**Comment by JCalderin91** [comment]
Eso es verdad, profesor, y bueno, no se repetirá.
Siempre aprendiendo.
Gracias, y saludos!

**Comment by ejdecena** [comment]
Siempre a tu orden Jesús. Feliz domingo :blush:
